### ISSUE TITLE
OpenAPI docs

### ISSUE THREAD

**Issue by FeldrinH** [codeborne/klite#24]
Are there any plans for supporting automatic OpenAPI docs generation or some other method to quickly generate API clients?

**Comment by angryziber** [comment]
Definitely there are at some point.
You are welcome to contribute OpenAPI module as well.

**Comment by angryziber** [comment]
The work has started on the `openapi` branch, you are welcome to review

**Comment by angryziber** [comment]
openapi module released in 1.6.0
