### ISSUE TITLE
Any plans about JWT?

### ISSUE THREAD

**Issue by advortsov** [codeborne/klite#29]
Are there any plans to create a module to work with JWT authentication?

**Comment by angryziber** [comment]
No plans right now, as JWT use cases can be very different.
You can just use any JWT parser and implement your own Before decorator that would do necessary checks that you need. It's just a few lines of code, most likely.

Or do you have an idea of some generic support that would be useful for many people?

**Comment by angryziber** [comment]
There is now `klite-oauth` module that includes JWT class, currently without signature verification yet. What do you think?
