### ISSUE TITLE
Move config and migrator to separate modules

### ISSUE THREAD

**Issue by advortsov** [codeborne/klite#6]
Suppose I want to use only the jdbc module in my project. 

In the current implementation, the jdbc module depends on the server module. Therefore, I will have to connect it as well. Also, the jdbc module contains a migrator, which I may not want to use (for example, my project already has a flyway)

Hence the question: Perhaps it is worth moving the config and the migrator into separate modules?

**Comment by angryziber** [comment]
Good point! I have already created a `core` module that is really small and is a required dependency of `jdbc` module.
So now, you can actually depend on `jdbc` without the `server`. Would be nice if you could very that.

As for DBMigrator, it is quite small and doesn't pull any additional dependencies, so probably is not a problem if unused.
Most other libraries contain 10-100x times more code that you don't actually use :-)

**Comment by angryziber** [comment]
Klite 1.4.3 was released with klite-jdbc usable standalone, without the server.
