### ISSUE TITLE
DB pool behaves incorrectly when I close the same connection multiple times

### ISSUE THREAD

**Issue by cbxp** [codeborne/klite#80]
#### Case:
I close DB connection multiple times

#### Expected result:
it's totally fine. The first `close()` call closes the connection, and the following `close()` calls are just ignored.

#### Actual result:
1. The connection is added to `pool.available` multiple times. 
2. As a result, subsequent calls to `pool.getConnection()` return the same connection multiple times.

#### Failing test:
```java
class PooledDataSourceTest {

  @Test fun `close same connection multiple times`() {
    val conn = pool.connection
    expect(pool.used.keys).toHaveSize(1)
    expect(pool.available).toHaveSize(0)

    conn.close()
    conn.close()
    conn.close()

    expect(pool.used.keys).toHaveSize(0)
    expect(pool.available).toHaveSize(1)  // Fails: pool.available.size is 3

    val conn2 = pool.connection
    expect(pool.connection).notToEqual(conn2) // Fails: it's the same connection
    expect(pool.connection).notToEqual(conn2)
  }
}
```

**Comment by angryziber** [comment]
Fixed, thanks
