### ISSUE TITLE
Cannot set custom logger in ".env" file

### ISSUE THREAD

**Issue by cbxp** [codeborne/klite#92]
I want to use custom logger.

I created class `CustomLogger`:
```kotlin
class CustomLogger(name: String) : KliteLogger(name) {
  ...
}
```

I added this class to file ".env":
```
LOGGER_CLASS=com.app.CustomLogger
```

#### Expected result:
Class `CustomLogger` is used for logging

#### Actual result:
The default class `KliteLogger` is used instead of `CustomLogger`.

#### Hint
The reason is that this line is executed BEFORE reading ".env" file:

```kotlin
class KliteLoggerFactory: ILoggerFactory {
  private val loggers = ConcurrentHashMap<String, Logger>()
  private val loggerConstructor = findConstructor(Config.optional("LOGGER_CLASS", KliteLogger::class.java.name))
```

**Comment by angryziber** [comment]
Make logger initialization lazy, making it possible to call `Config.useEnvFile()` before first logging and let it affect the logger implementatoin
