### ISSUE TITLE
Application restart is slow

### ISSUE THREAD

**Issue by cbxp** [codeborne/klite#96]
During development, we often need to restart the application.
But every restart takes 3+ seconds.

It's caused by default value `gracefulStopDelaySec=3` in `klite.Server.start()`.

I assume this could be timeout (maximum time, **up to** 3 seconds).
But the application **always waits for 3 seconds**, even if there is not running requests/jobs.

**Comment by angryziber** [comment]
This seems to be a bug in JDK HttpServer (ServerImpl), which according to the javadoc could terminate earlier, but in reality always waits as long as the passed delay...
